### ISSUE TITLE
Thanks your for this !

### ISSUE THREAD

**Issue by m-code-official** [OwnTheSite/docker-wordpress-localhost#1]
Thank you very much or your script.
I was looking for something for a while know and all is working !

I have a question regarding the site health status where the cURL through the API is connection refused

Do you have any idea on how I can allow this connection?

Thanks for your help

<img width="825" alt="Capture d’écran 2023-10-12 à 18 58 53" src="https://github.com/khairulimran-97/docker-wordpress-localhost/assets/46845666/1f7682eb-1e97-48ee-b134-7a7973d3fc65">

**Comment by khairulimran-97** [comment]
Sorry, I haven't encountered that issue before, but you might find a solution in this community thread: https://community.localwp.com/t/curl-error-7-failed-to-connect-to-www-domain-dev-port-443-connection-refused/4066

**Comment by m-code-official** [comment]
Perfect I'll check this out thanks
